apiVersion: v1
kind: Namespace
metadata:
  name: scholarship-dev
  labels:
    environment: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scholarship-backend
  namespace: scholarship-dev
  labels:
    app: scholarship-backend
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scholarship-backend
  template:
    metadata:
      labels:
        app: scholarship-backend
    spec:
      containers:
      - name: backend
        image: scholarship-backend:dev
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: scholarship-secrets
              key: database-url
        - name: REDIS_URL
          value: "redis://scholarship-redis:6379/0"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: scholarship-secrets
              key: jwt-secret
        - name: ENVIRONMENT
          value: "development"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scholarship-frontend
  namespace: scholarship-dev
  labels:
    app: scholarship-frontend
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scholarship-frontend
  template:
    metadata:
      labels:
        app: scholarship-frontend
    spec:
      containers:
      - name: frontend
        image: scholarship-frontend:dev
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://scholarship-backend:8000/api/v1"
        - name: NODE_ENV
          value: "development"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scholarship-postgres
  namespace: scholarship-dev
  labels:
    app: scholarship-postgres
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scholarship-postgres
  template:
    metadata:
      labels:
        app: scholarship-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "scholarship_dev"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: scholarship-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: scholarship-secrets
              key: postgres-password
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scholarship-redis
  namespace: scholarship-dev
  labels:
    app: scholarship-redis
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scholarship-redis
  template:
    metadata:
      labels:
        app: scholarship-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        command:
        - redis-server
        - --maxmemory
        - 256mb
        - --maxmemory-policy
        - allkeys-lru
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: scholarship-backend
  namespace: scholarship-dev
  labels:
    app: scholarship-backend
spec:
  selector:
    app: scholarship-backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: scholarship-frontend
  namespace: scholarship-dev
  labels:
    app: scholarship-frontend
spec:
  selector:
    app: scholarship-frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: scholarship-postgres
  namespace: scholarship-dev
  labels:
    app: scholarship-postgres
spec:
  selector:
    app: scholarship-postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: scholarship-redis
  namespace: scholarship-dev
  labels:
    app: scholarship-redis
spec:
  selector:
    app: scholarship-redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: scholarship-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: Secret
metadata:
  name: scholarship-secrets
  namespace: scholarship-dev
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  database-url: cG9zdGdyZXNxbCthc3luY3BnOi8vc2Nob2xhcnNoaXBfdXNlcjpkZXZfcGFzc3dvcmRAc2Nob2xhcnNoaXAtcG9zdGdyZXM6NTQzMi9zY2hvbGFyc2hpcF9kZXY=
  postgres-user: c2Nob2xhcnNoaXBfdXNlcg==
  postgres-password: ZGV2X3Bhc3N3b3Jk
  jwt-secret: ZGV2X2p3dF9zZWNyZXRfa2V5XzEyMzQ1Njc4OTA= 