apiVersion: v2
name: scholarship-system
description: A Helm chart for Scholarship Application and Approval Management System
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - scholarship
  - education
  - application
  - fastapi
  - nextjs
  - postgresql

home: https://scholarship.edu.tw
sources:
  - https://github.com/your-org/scholarship-system

maintainers:
  - name: Development Team
    email: dev@scholarship.edu.tw

annotations:
  category: Education
  licenses: MIT

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x" 
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: nginx-ingress
    version: "4.x.x"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.enabled 