"""seed academy data

Revision ID: 09a6cf986f5c
Revises: 3453e6861885
Create Date: 2025-10-05 01:40:01.637586

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09a6cf986f5c"
down_revision: Union[str, None] = "3453e6861885"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """填充學院與系所資料"""

    # 學院資料
    ACADEMY_DATA = [
        {"code": "E", "name": "電機學院", "name_en": "College of Electrical and Computer Engineering"},
        {"code": "Y", "name": "電資學院", "name_en": "College of Electrical Engineering and Computer Science"},
        {"code": "C", "name": "資訊學院", "name_en": "College of Computer Science"},
        {"code": "I", "name": "工學院", "name_en": "College of Engineering"},
        {"code": "S", "name": "科管學院", "name_en": "College of Management"},
        {"code": "M", "name": "管理學院", "name_en": "College of Management"},
        {"code": "A", "name": "人社學院", "name_en": "College of Humanities and Social Sciences"},
        {"code": "B", "name": "生科學院", "name_en": "College of Biological Science and Technology"},
        {"code": "O", "name": "客家學院", "name_en": "College of Hakka Studies"},
        {"code": "D", "name": "光電學院", "name_en": "College of Photonics"},
        {"code": "K", "name": "半導體學院", "name_en": "College of Semiconductor Research"},
        {"code": "L", "name": "永續學院", "name_en": "College of Sustainability"},
        {"code": "G", "name": "智慧學院", "name_en": "College of AI"},
        {"code": "F", "name": "國際半導體學院", "name_en": "International College of Semiconductor Technology"},
        {"code": "J", "name": "跨域學院", "name_en": "College of Interdisciplinary Studies"},
        {"code": "X", "name": "產學創新學院", "name_en": "College of Industry-Academia Innovation"},
        {"code": "~", "name": "智能系統學院", "name_en": "College of Intelligent Systems"},
        {"code": "1", "name": "理學院", "name_en": "College of Science"},
        {"code": "2", "name": "工學院", "name_en": "College of Engineering"},
        {"code": "3", "name": "管理學院", "name_en": "College of Management"},
        {"code": "4", "name": "人文社會學院", "name_en": "College of Humanities and Social Sciences"},
        {"code": "5", "name": "生命科學院", "name_en": "College of Life Science"},
        {"code": "6", "name": "電資學院", "name_en": "College of Electrical Engineering and Computer Science"},
        {"code": "7", "name": "科技法律學院", "name_en": "College of Technology Law"},
        {"code": "Z", "name": "服務學習專業知能學程", "name_en": "Service Learning Program"},
        {"code": "0", "name": "未分類", "name_en": "Unclassified"},
        {"code": "P", "name": "總務處", "name_en": "General Affairs Office"},
        {"code": "*", "name": "海外教育專班", "name_en": "Overseas Education Program"},
        {"code": "^", "name": "全校性單位", "name_en": "University-wide Units"},
    ]

    # 系所與學院對應資料
    DEPARTMENT_MAPPING = [
        {"code": "0U4", "academy_code": "^", "name": "華語中心"},
        {"code": "0U5", "academy_code": "^", "name": "通識教育中心"},
        {"code": "11D", "academy_code": "D", "name": "光電工程學系"},
        {"code": "11E", "academy_code": "E", "name": "電機工程學系"},
        {"code": "11F", "academy_code": "E", "name": "電信工程學系"},
        {"code": "11G", "academy_code": "C", "name": "資訊工程學系"},
        {"code": "11H", "academy_code": "E", "name": "電子工程學系"},
        {"code": "11I", "academy_code": "I", "name": "控制工程學系"},
        {"code": "11K", "academy_code": "I", "name": "土木工程學系"},
        {"code": "11L", "academy_code": "I", "name": "機械工程學系"},
        {"code": "11M", "academy_code": "S", "name": "工業工程與管理學系"},
        {"code": "11N", "academy_code": "I", "name": "材料科學與工程學系"},
        {"code": "11P", "academy_code": "1", "name": "應用數學系"},
        {"code": "11Q", "academy_code": "1", "name": "應用化學系"},
        {"code": "11R", "academy_code": "1", "name": "物理研究所"},
        {"code": "11S", "academy_code": "M", "name": "管理科學系"},
        {"code": "11T", "academy_code": "S", "name": "運輸科技與管理學系"},
        {"code": "11U", "academy_code": "A", "name": "傳播研究所"},
        {"code": "11V", "academy_code": "B", "name": "生物科技學系"},
        {"code": "11X", "academy_code": "I", "name": "環境工程研究所"},
        {"code": "11Y", "academy_code": "B", "name": "生物資訊及系統生物研究所"},
        {"code": "11Z", "academy_code": "I", "name": "建築研究所"},
        {"code": "12A", "academy_code": "E", "name": "電子物理學系"},
        {"code": "12B", "academy_code": "C", "name": "資訊科學與工程研究所"},
        {"code": "12C", "academy_code": "I", "name": "統計學研究所"},
        {"code": "12D", "academy_code": "S", "name": "管理學院碩士在職專班"},
        {"code": "12E", "academy_code": "E", "name": "電機學院碩士在職專班"},
        {"code": "12F", "academy_code": "I", "name": "工學院專班"},
        {"code": "12G", "academy_code": "S", "name": "科技管理研究所"},
        {"code": "12H", "academy_code": "E", "name": "電控工程研究所"},
        {"code": "12I", "academy_code": "I", "name": "奈米科技碩士學位學程"},
        {"code": "12J", "academy_code": "Y", "name": "電信工程研究所"},
        {"code": "12K", "academy_code": "M", "name": "財務金融研究所"},
        {"code": "12L", "academy_code": "M", "name": "資訊管理研究所"},
        {"code": "12M", "academy_code": "A", "name": "教育研究所"},
        {"code": "12N", "academy_code": "A", "name": "英語教學研究所"},
        {"code": "12O", "academy_code": "A", "name": "社會與文化研究所"},
        {"code": "12P", "academy_code": "C", "name": "網路工程研究所"},
        {"code": "12Q", "academy_code": "S", "name": "科技法律研究所"},
        {"code": "12R", "academy_code": "A", "name": "外國語文學系"},
        {"code": "12S", "academy_code": "B", "name": "分子醫學與生物工程研究所"},
        {"code": "12T", "academy_code": "I", "name": "加速器光源科技與應用碩士學位學程"},
        {"code": "12U", "academy_code": "B", "name": "生命科學系"},
        {"code": "12V", "academy_code": "S", "name": "經營管理碩士學程"},
        {"code": "12W", "academy_code": "C", "name": "資訊管理與財務金融系 財務金融碩士班"},
        {"code": "12X", "academy_code": "M", "name": "資訊管理與財務金融系 資訊管理碩士班"},
        {"code": "12Y", "academy_code": "I", "name": "工業工程與管理學系工業工程與管理碩士班"},
        {"code": "12Z", "academy_code": "S", "name": "工業工程與管理學系管理學碩士班"},
        {"code": "13A", "academy_code": "S", "name": "工業工程與管理學系管理學博士班"},
        {"code": "13B", "academy_code": "I", "name": "工業工程與管理學系工業工程與管理博士班"},
        {"code": "13C", "academy_code": "I", "name": "國際半導體產業學院碩士班"},
        {"code": "13D", "academy_code": "C", "name": "多媒體工程研究所"},
        {"code": "13E", "academy_code": "E", "name": "光電系統研究所"},
        {"code": "13F", "academy_code": "I", "name": "奈米與微系統工程碩士學位學程"},
        {"code": "13G", "academy_code": "^", "name": "師資培育中心"},
        {"code": "13H", "academy_code": "I", "name": "前瞻功能材料產業博士學位學程"},
        {"code": "13I", "academy_code": "E", "name": "前瞻半導體研究所"},
        {"code": "13J", "academy_code": "I", "name": "前瞻跨領域基礎科學博士學位學程"},
        {"code": "13K", "academy_code": "I", "name": "國際半導體產業學院博士班"},
        {"code": "13L", "academy_code": "B", "name": "跨領域分子科學國際研究生博士學位學程"},
        {"code": "13M", "academy_code": "Y", "name": "電資學士班"},
        {"code": "13N", "academy_code": "A", "name": "音樂研究所"},
        {"code": "13O", "academy_code": "A", "name": "應用藝術研究所"},
        {"code": "13P", "academy_code": "C", "name": "生醫工程研究所"},
        {"code": "13Q", "academy_code": "B", "name": "跨領域神經科學博士學位學程國際研究生博士班"},
        {"code": "13R", "academy_code": "B", "name": "跨領域轉譯醫學博士學位學程"},
        {"code": "13S", "academy_code": "I", "name": "產業安全與防災學士學位學程"},
        {"code": "13T", "academy_code": "O", "name": "客家文化學院學士班"},
        {"code": "13U", "academy_code": "O", "name": "人文社會學系"},
        {"code": "13V", "academy_code": "O", "name": "傳播與科技學系"},
        {"code": "13W", "academy_code": "O", "name": "族群與文化碩士班"},
        {"code": "13X", "academy_code": "O", "name": "客家社會與文化碩士在職專班"},
        {"code": "13Y", "academy_code": "B", "name": "生物科技學系生物資訊及系統生物碩士班"},
        {"code": "13Z", "academy_code": "B", "name": "生物科技學系分子醫學與生物工程碩士班"},
        {"code": "14A", "academy_code": "B", "name": "生物科技學系生物科技碩士班"},
        {"code": "14B", "academy_code": "B", "name": "生物科技學系生物科技博士班"},
        {"code": "14C", "academy_code": "I", "name": "環境工程研究所博士班"},
        {"code": "14D", "academy_code": "I", "name": "環境工程研究所碩士班"},
        {"code": "14E", "academy_code": "C", "name": "資訊科學與工程研究所博士班"},
        {"code": "14F", "academy_code": "C", "name": "資訊科學與工程研究所碩士班"},
        {"code": "14G", "academy_code": "B", "name": "生物資訊及系統生物研究所博士班"},
        {"code": "14H", "academy_code": "I", "name": "建築研究所博士班"},
        {"code": "14I", "academy_code": "I", "name": "建築研究所碩士班"},
        {"code": "14J", "academy_code": "D", "name": "顯示科技研究所"},
        {"code": "14K", "academy_code": "C", "name": "資訊學院碩士在職專班"},
        {"code": "14L", "academy_code": "I", "name": "工學院碩士在職專班產業安全與防災組"},
        {"code": "14M", "academy_code": "C", "name": "資訊學院IPP碩士學位學程"},
        {"code": "14N", "academy_code": "M", "name": "經營管理碩士班(EMBA)"},
        {"code": "14O", "academy_code": "D", "name": "影像與生醫光電研究所"},
        {"code": "14P", "academy_code": "I", "name": "工程技術與管理學士學位學程"},
        {"code": "14Q", "academy_code": "E", "name": "電機工程學系乙組"},
        {"code": "14R", "academy_code": "C", "name": "智慧計算與科技研究所"},
        {"code": "14S", "academy_code": "E", "name": "電機工程學系甲組"},
        {"code": "14T", "academy_code": "E", "name": "電機工程學系丙組"},
        {"code": "14U", "academy_code": "E", "name": "電子研究所"},
        {"code": "14V", "academy_code": "E", "name": "電子研究所乙組"},
        {"code": "14W", "academy_code": "E", "name": "電子研究所甲組"},
        {"code": "14X", "academy_code": "E", "name": "電機學院學士班"},
        {"code": "14Y", "academy_code": "E", "name": "電機學院產業研發碩士班"},
        {"code": "14Z", "academy_code": "E", "name": "智能系統研究所"},
        {"code": "15A", "academy_code": "E", "name": "電信研究所"},
        {"code": "15B", "academy_code": "I", "name": "工學院學士班"},
        {"code": "15C", "academy_code": "I", "name": "土木工程學系土木與防災乙組"},
        {"code": "15D", "academy_code": "I", "name": "土木工程學系土木與防災甲組"},
        {"code": "15E", "academy_code": "I", "name": "土木工程學系"},
        {"code": "15F", "academy_code": "I", "name": "機械工程學系甲組"},
        {"code": "15G", "academy_code": "I", "name": "機械工程學系乙組"},
        {"code": "15H", "academy_code": "I", "name": "材料科學與工程學系甲組"},
        {"code": "15I", "academy_code": "I", "name": "材料科學與工程學系乙組"},
        {"code": "15J", "academy_code": "I", "name": "工學院精密與自動化工程學士學位學程"},
        {"code": "15K", "academy_code": "1", "name": "理學院科學學士學位學程"},
        {"code": "15L", "academy_code": "1", "name": "應用數學系數學建模與科學計算碩士班"},
        {"code": "15M", "academy_code": "1", "name": "應用數學系應用數學碩士班"},
        {"code": "15N", "academy_code": "1", "name": "應用化學系分子科學碩士班"},
        {"code": "15O", "academy_code": "1", "name": "應用化學系應用化學碩士班"},
        {"code": "15P", "academy_code": "1", "name": "物理研究所"},
        {"code": "15Q", "academy_code": "1", "name": "理學院跨領域理學士學位學程"},
        {"code": "15R", "academy_code": "M", "name": "管理學院學士班"},
        {"code": "15S", "academy_code": "M", "name": "管理學院管理學碩士學位學程"},
        {"code": "15T", "academy_code": "S", "name": "運輸與物流管理學系交通運輸碩士班"},
        {"code": "15U", "academy_code": "S", "name": "運輸與物流管理學系物流管理碩士班"},
        {"code": "15V", "academy_code": "S", "name": "傳播與科技學系傳播碩士班"},
        {"code": "15W", "academy_code": "S", "name": "傳播與科技學系傳播與科技碩士班"},
        {"code": "15X", "academy_code": "M", "name": "管理學院產業研發碩士班"},
        {"code": "15Y", "academy_code": "S", "name": "科技管理學院學士班"},
        {"code": "15Z", "academy_code": "A", "name": "外國語文學系外國文學與語言學碩士班"},
        {"code": "16A", "academy_code": "A", "name": "外國語文學系語言學與英語教學碩士班"},
        {"code": "16B", "academy_code": "A", "name": "社會與文化研究所碩士班"},
        {"code": "16C", "academy_code": "A", "name": "人文社會學士學位學程"},
        {"code": "16D", "academy_code": "A", "name": "英語教學研究所英語教學碩士班"},
        {"code": "16E", "academy_code": "A", "name": "英語教學研究所數位學習碩士在職專班"},
        {"code": "16F", "academy_code": "B", "name": "生命科學院學士班"},
        {"code": "16G", "academy_code": "B", "name": "生物科技學系生物科技與生物資訊碩士班"},
        {"code": "16H", "academy_code": "D", "name": "光電學院學士班"},
        {"code": "16I", "academy_code": "D", "name": "光電工程學系光電工程碩士班"},
        {"code": "16J", "academy_code": "D", "name": "光電工程學系光電系統碩士班"},
        {"code": "16K", "academy_code": "D", "name": "照明與能源光電研究所"},
        {"code": "16L", "academy_code": "D", "name": "光電學院碩士在職專班"},
        {"code": "16M", "academy_code": "C", "name": "資訊學院學士班"},
        {"code": "16N", "academy_code": "C", "name": "資訊工程學系資訊工程碩士班"},
        {"code": "16O", "academy_code": "C", "name": "資訊工程學系網路與多媒體工程碩士班"},
        {"code": "16P", "academy_code": "Y", "name": "電機資訊學士班"},
        {"code": "16Q", "academy_code": "S", "name": "科技管理研究所科技管理碩士班"},
        {"code": "16R", "academy_code": "S", "name": "科技管理研究所智慧醫療與健康資訊碩士班"},
        {"code": "16S", "academy_code": "M", "name": "管理科學系資訊管理組"},
        {"code": "16T", "academy_code": "M", "name": "管理科學系作業研究組"},
        {"code": "16U", "academy_code": "S", "name": "科技法律學院學士班"},
        {"code": "16V", "academy_code": "S", "name": "科技法律學院科技法律碩士班"},
        {"code": "16W", "academy_code": "S", "name": "科技法律學院科技法律博士班"},
        {"code": "16X", "academy_code": "C", "name": "資訊工程學系資訊工程碩士在職專班"},
        {"code": "16Y", "academy_code": "I", "name": "土木工程學系碩士在職專班"},
        {"code": "16Z", "academy_code": "I", "name": "防災與水環境研究所碩士在職專班"},
        {"code": "17A", "academy_code": "O", "name": "客家文化學院人文社會學系人文社會碩士班"},
        {"code": "17B", "academy_code": "O", "name": "客家文化學院人文社會學系族群與文化碩士班"},
        {"code": "17C", "academy_code": "E", "name": "奈米與微系統工程碩士學位學程"},
        {"code": "17D", "academy_code": "D", "name": "光電學院學士班丙組"},
        {"code": "17E", "academy_code": "D", "name": "光電學院學士班乙組"},
        {"code": "17F", "academy_code": "D", "name": "光電學院學士班甲組"},
        {"code": "17G", "academy_code": "E", "name": "電機學院學士班乙組"},
        {"code": "17H", "academy_code": "E", "name": "電機學院學士班甲組"},
        {"code": "17I", "academy_code": "C", "name": "資訊學院學士班乙組"},
        {"code": "17J", "academy_code": "C", "name": "資訊學院學士班甲組"},
        {"code": "17K", "academy_code": "I", "name": "工學院學士班丙組"},
        {"code": "17L", "academy_code": "I", "name": "工學院學士班乙組"},
        {"code": "17M", "academy_code": "I", "name": "工學院學士班甲組"},
        {"code": "17N", "academy_code": "M", "name": "管理學院學士班丙組"},
        {"code": "17O", "academy_code": "M", "name": "管理學院學士班乙組"},
        {"code": "17P", "academy_code": "M", "name": "管理學院學士班甲組"},
        {"code": "17Q", "academy_code": "B", "name": "生命科學院學士班丙組"},
        {"code": "17R", "academy_code": "B", "name": "生命科學院學士班乙組"},
        {"code": "17S", "academy_code": "B", "name": "生命科學院學士班甲組"},
        {"code": "17T", "academy_code": "1", "name": "理學院科學學士學位學程丙組"},
        {"code": "17U", "academy_code": "1", "name": "理學院科學學士學位學程乙組"},
        {"code": "17V", "academy_code": "1", "name": "理學院科學學士學位學程甲組"},
        {"code": "17W", "academy_code": "Y", "name": "電機資訊學士班甲組"},
        {"code": "17X", "academy_code": "Y", "name": "電機資訊學士班乙組"},
        {"code": "17Y", "academy_code": "Y", "name": "電機資訊學士班丙組"},
        {"code": "17Z", "academy_code": "S", "name": "科技管理學院學士班丙組"},
        {"code": "18A", "academy_code": "S", "name": "科技管理學院學士班乙組"},
        {"code": "18B", "academy_code": "S", "name": "科技管理學院學士班甲組"},
        {"code": "18C", "academy_code": "S", "name": "科技法律學院學士班甲組"},
        {"code": "18D", "academy_code": "S", "name": "科技法律學院學士班乙組"},
        {"code": "18E", "academy_code": "S", "name": "科技法律學院學士班丙組"},
        {"code": "18F", "academy_code": "A", "name": "人文社會學士學位學程甲組"},
        {"code": "18G", "academy_code": "A", "name": "人文社會學士學位學程乙組"},
        {"code": "18H", "academy_code": "A", "name": "人文社會學士學位學程丙組"},
        {"code": "18I", "academy_code": "O", "name": "客家文化學院學士班甲組"},
        {"code": "18J", "academy_code": "O", "name": "客家文化學院學士班乙組"},
        {"code": "18K", "academy_code": "Y", "name": "電機資訊國際學士班"},
        {"code": "18L", "academy_code": "I", "name": "國際半導體產業學院學士班"},
        {"code": "18M", "academy_code": "K", "name": "半導體學院學士班"},
        {"code": "18N", "academy_code": "E", "name": "電機學院國際碩士學位學程"},
        {"code": "18O", "academy_code": "I", "name": "工學院國際碩士學位學程"},
        {"code": "18P", "academy_code": "A", "name": "文化研究國際碩士學位學程(台聯大)"},
        {"code": "18Q", "academy_code": "D", "name": "光電學院國際碩士學位學程"},
        {"code": "18R", "academy_code": "M", "name": "管理學院國際經營管理碩士學位學程"},
        {"code": "18S", "academy_code": "M", "name": "管理學院國際財務金融碩士學位學程"},
        {"code": "18T", "academy_code": "B", "name": "生命科學院國際碩士學位學程"},
        {"code": "18U", "academy_code": "I", "name": "國際半導體產業學院碩士在職專班"},
        {"code": "18V", "academy_code": "I", "name": "工學院碩士在職專班工程技術與管理組"},
        {"code": "18W", "academy_code": "E", "name": "電機學院碩士在職專班電機工程組"},
        {"code": "18X", "academy_code": "E", "name": "電機學院碩士在職專班電子工程組"},
        {"code": "18Y", "academy_code": "E", "name": "電機學院碩士在職專班資訊工程組"},
        {"code": "18Z", "academy_code": "D", "name": "光電學院碩士在職專班"},
        {"code": "19A", "academy_code": "I", "name": "防災工程碩士在職專班"},
        {"code": "19B", "academy_code": "M", "name": "高階主管管理碩士學程(EMBA)"},
        {"code": "19C", "academy_code": "M", "name": "管理學院碩士在職專班資訊管理組"},
        {"code": "19D", "academy_code": "M", "name": "管理學院碩士在職專班財務金融組"},
        {"code": "19E", "academy_code": "M", "name": "管理學院碩士在職專班經營管理組"},
        {"code": "19F", "academy_code": "M", "name": "管理學院碩士在職專班科技管理組"},
        {"code": "19G", "academy_code": "A", "name": "數位內容製作碩士學位學程"},
        {"code": "19H", "academy_code": "A", "name": "教育研究所教育行政碩士在職專班"},
        {"code": "19I", "academy_code": "A", "name": "教育研究所學習科技碩士在職專班"},
        {"code": "19J", "academy_code": "K", "name": "半導體學院產業碩士專班"},
        {"code": "19K", "academy_code": "E", "name": "國際半導體產業學院產業碩士專班"},
        {"code": "19L", "academy_code": "M", "name": "管理學院MBA學位學程"},
        {"code": "19M", "academy_code": "C", "name": "前瞻網路智能與應用國際博士學位學程"},
        {"code": "19N", "academy_code": "E", "name": "跨領域前瞻光電博士學位學程"},
        {"code": "19O", "academy_code": "C", "name": "資訊學院前瞻資通訊博士學位學程"},
        {"code": "19P", "academy_code": "I", "name": "跨領域永續科學與工程國際博士學位學程"},
        {"code": "19Q", "academy_code": "M", "name": "社群網路與人智計算國際研究生博士學位學程"},
        {"code": "19R", "academy_code": "C", "name": "跨領域資訊科技國際研究生博士學位學程"},
        {"code": "20A", "academy_code": "1", "name": "理學院跨領域科學國際碩士學位學程"},
        {"code": "20B", "academy_code": "1", "name": "理學院跨領域科學國際博士學位學程"},
        {"code": "20C", "academy_code": "I", "name": "國際半導體產業學院博士在職專班"},
        {"code": "20D", "academy_code": "A", "name": "文創藝術與數位行銷碩士學位學程"},
        {"code": "21A", "academy_code": "1", "name": "應用數學系"},
        {"code": "21B", "academy_code": "1", "name": "應用化學系"},
        {"code": "21C", "academy_code": "C", "name": "資訊工程學系"},
        {"code": "21D", "academy_code": "E", "name": "電機工程學系"},
        {"code": "21E", "academy_code": "I", "name": "土木工程學系"},
        {"code": "21F", "academy_code": "I", "name": "機械工程學系"},
        {"code": "21G", "academy_code": "S", "name": "工業工程與管理學系"},
        {"code": "21H", "academy_code": "I", "name": "材料科學與工程學系"},
        {"code": "21I", "academy_code": "M", "name": "管理科學系"},
        {"code": "21J", "academy_code": "S", "name": "運輸與物流管理學系"},
        {"code": "21K", "academy_code": "S", "name": "資訊管理與財務金融學系資訊管理組"},
        {"code": "21L", "academy_code": "M", "name": "資訊管理與財務金融學系財務金融組"},
        {"code": "21M", "academy_code": "B", "name": "生命科學系"},
        {"code": "21N", "academy_code": "A", "name": "外國語文學系"},
        {"code": "21O", "academy_code": "D", "name": "光電工程學系"},
        {"code": "21P", "academy_code": "E", "name": "電子物理學系"},
        {"code": "22A", "academy_code": "C", "name": "資訊學院國際碩士學位學程"},
    ]

    # 插入學院資料
    conn = op.get_bind()
    for academy in ACADEMY_DATA:
        conn.execute(
            sa.text(
                """
                INSERT INTO academies (code, name, name_en)
                VALUES (:code, :name, :name_en)
                ON CONFLICT (code) DO UPDATE SET
                    name = EXCLUDED.name,
                    name_en = EXCLUDED.name_en
            """
            ),
            academy,
        )

    # 更新系所與學院關聯
    for dept in DEPARTMENT_MAPPING:
        conn.execute(
            sa.text(
                """
                UPDATE departments
                SET academy_code = :academy_code
                WHERE code = :code
            """
            ),
            dept,
        )


def downgrade() -> None:
    """清除學院資料的關聯"""
    conn = op.get_bind()

    # 清除系所的學院關聯
    conn.execute(sa.text("UPDATE departments SET academy_code = NULL"))
