"""Add scholarship_type_id to email_templates + replace single-key unique with compound.

Closes the schema half of issue #647 — per-scholarship email templates were
the missing piece blocking 5 of the 6 ``/admin/scholarship-email-templates/*``
endpoints from working.

# Schema changes

1. Add column ``scholarship_type_id INTEGER NULL`` with FK to ``scholarship_types.id``.
   NULL means "generic template" (applies to all scholarships).
2. Drop the existing single-column unique constraint on ``key``. Defensive:
   the constraint name is auto-generated by alembic from the model's
   ``Column(... unique=True)``, so we look it up by column rather than
   hard-coding the name.
3. Add compound unique on ``(key, scholarship_type_id)``. Postgres allows
   multiple NULLs in a unique constraint by default, so generic templates
   and per-scholarship overrides for the same key coexist.

# Safety

- ``op.add_column`` is non-destructive; existing rows get NULL = generic.
- The constraint swap is the only mutating change. If the lookup of the
  old constraint name fails (e.g., on a fresh DB where the unique was
  created via the new schema), the migration falls back gracefully.

Revision ID: email_tpl_scholar_type_001
Revises: merge_20260515_heads
Create Date: 2026-05-15
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "email_tpl_scholar_type_001"
down_revision: Union[str, Sequence[str], None] = "merge_20260515_heads"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _existing_key_unique_constraint_name(inspector) -> tuple:
    """Return (name, kind) for the existing single-column unique on ``key``.

    kind is ``"constraint"`` when found via get_unique_constraints (can be
    dropped with op.drop_constraint), or ``"index"`` when found via
    get_indexes (must be dropped with op.drop_index). Returns (None, None)
    if neither is found (fresh DB built from the new model).

    Returning the kind avoids the try/except anti-pattern where
    op.drop_constraint fails with UndefinedObject, the PostgreSQL transaction
    enters aborted state, and the fallback op.drop_index also fails.
    """
    for c in inspector.get_unique_constraints("email_templates"):
        if c.get("column_names") == ["key"]:
            return c["name"], "constraint"
    for ix in inspector.get_indexes("email_templates"):
        if ix.get("unique") and ix.get("column_names") == ["key"]:
            return ix["name"], "index"
    return None, None


def _fks_targeting_email_templates_key(inspector, table_name: str) -> list:
    """Return all FK names on ``table_name`` that reference ``email_templates.key``.

    Multiple tables had FKs to ``email_templates.key`` (added by the SQLAlchemy
    metadata ``create_all`` in migration ``59b65a4de996`` and by
    ``c5d8f9a2b3e1``). All of them block dropping the single-column unique on
    ``email_templates.key``. The application layer handles override-vs-generic
    template lookup, so dropping these DB-level FKs is safe.
    """
    if table_name not in inspector.get_table_names():
        return []
    return [
        fk.get("name")
        for fk in inspector.get_foreign_keys(table_name)
        if fk.get("referred_table") == "email_templates" and fk.get("referred_columns") == ["key"] and fk.get("name")
    ]


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    existing_columns = {c["name"] for c in inspector.get_columns("email_templates")}

    # 1. Drop every FK that targets ``email_templates.key``. PostgreSQL won't
    #    let us replace the single-column unique on ``key`` with a compound
    #    unique while any FK references it. The known sources are
    #    ``email_automation_rules.template_key`` (migration c5d8f9a2b3e1),
    #    ``email_history.template_key`` and ``scheduled_emails.template_key``
    #    (created by the SQLAlchemy ``create_all`` in 59b65a4de996). Look them
    #    up dynamically so the auto-generated FK names don't have to be known.
    for table_name in ("email_automation_rules", "email_history", "scheduled_emails"):
        for fk_name in _fks_targeting_email_templates_key(inspector, table_name):
            op.drop_constraint(fk_name, table_name, type_="foreignkey")

    # 2. Add scholarship_type_id column + FK + supporting index.
    if "scholarship_type_id" not in existing_columns:
        op.add_column(
            "email_templates",
            sa.Column("scholarship_type_id", sa.Integer(), nullable=True),
        )
        op.create_foreign_key(
            "fk_email_templates_scholarship_type",
            "email_templates",
            "scholarship_types",
            ["scholarship_type_id"],
            ["id"],
        )
        op.create_index(
            "ix_email_templates_scholarship_type_id",
            "email_templates",
            ["scholarship_type_id"],
        )

    # 3. Drop the auto-generated single-column unique on ``key``.
    existing_unique_name, unique_kind = _existing_key_unique_constraint_name(inspector)
    if existing_unique_name:
        # Use the correct DDL based on how the unique was created. Mixing them
        # (e.g., calling op.drop_constraint on a UNIQUE INDEX) raises
        # UndefinedObject and aborts the transaction before the fallback runs.
        if unique_kind == "constraint":
            op.drop_constraint(existing_unique_name, "email_templates", type_="unique")
        else:
            op.drop_index(existing_unique_name, table_name="email_templates")

    # 4. Add the compound unique constraint.
    existing_constraint_names = {c["name"] for c in inspector.get_unique_constraints("email_templates")}
    if "uq_email_templates_key_scholarship" not in existing_constraint_names:
        op.create_unique_constraint(
            "uq_email_templates_key_scholarship",
            "email_templates",
            ["key", "scholarship_type_id"],
        )


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    existing_constraint_names = {c["name"] for c in inspector.get_unique_constraints("email_templates")}
    if "uq_email_templates_key_scholarship" in existing_constraint_names:
        op.drop_constraint("uq_email_templates_key_scholarship", "email_templates", type_="unique")

    # Restore the auto-generated single-column unique on ``key`` (matches
    # the pre-upgrade Column(..., unique=True) form).
    op.create_unique_constraint("email_templates_key_key", "email_templates", ["key"])

    existing_indexes = {ix["name"] for ix in inspector.get_indexes("email_templates")}
    if "ix_email_templates_scholarship_type_id" in existing_indexes:
        op.drop_index("ix_email_templates_scholarship_type_id", table_name="email_templates")

    # Best-effort FK drop — name was set explicitly above so this is stable.
    try:
        op.drop_constraint("fk_email_templates_scholarship_type", "email_templates", type_="foreignkey")
    except Exception:
        pass

    existing_columns = {c["name"] for c in inspector.get_columns("email_templates")}
    if "scholarship_type_id" in existing_columns:
        op.drop_column("email_templates", "scholarship_type_id")

    # Restore FKs on the three template_key columns → email_templates.key
    # so post-downgrade schema matches the pre-upgrade state.
    existing_tables = inspector.get_table_names()
    for table_name in ("email_automation_rules", "email_history", "scheduled_emails"):
        if table_name in existing_tables:
            op.create_foreign_key(
                f"fk_{table_name}_template_key",
                table_name,
                "email_templates",
                ["template_key"],
                ["key"],
            )
