/**
 * Tests for `lib/email-preview-store.ts`.
 *
 * The email preview store backs the admin "preview before send" flow:
 * - POST creates a preview, returns an ID
 * - GET fetches the preview by ID
 * - TTL ensures stale previews are GC'd after 10 minutes
 *
 * The store is pinned to `globalThis` (not module-level) because
 * Next.js compiles each API route into its own bundle — a plain Map
 * would duplicate and POST/GET handlers would see different Maps.
 *
 * Regression risks:
 * - ID collisions (two stores share IDs) → preview shows wrong content
 * - TTL too long → memory leak with thousands of in-flight previews
 * - TTL too short → admin clicks preview, gets 404 after typing
 *
 * 6 cases.
 */
import { storePreview, getPreview } from "../email-preview-store";

describe("email-preview-store", () => {
  beforeEach(() => {
    // Reset the global store between tests — important because the store
    // is pinned to globalThis to survive bundle splits.
    (globalThis as any).__emailPreviewStore?.clear();
    jest.useFakeTimers();
  });

  afterEach(() => {
    jest.useRealTimers();
  });

  it("storePreview returns a non-empty ID", () => {
    /** ID is generated by crypto.randomUUID() — pin that the wrapper
     * returns a usable string (not undefined / empty)."""
     */
    const id = storePreview("<p>Hello</p>");
    expect(typeof id).toBe("string");
    expect(id.length).toBeGreaterThan(0);
  });

  it("getPreview retrieves the stored HTML by ID", () => {
    /** Round-trip: store HTML → get same HTML back. */
    const html = "<p>Email body with <strong>formatting</strong></p>";
    const id = storePreview(html);
    expect(getPreview(id)).toBe(html);
  });

  it("getPreview returns undefined for unknown ID", () => {
    /** Frontend uses this to detect expired/missing previews and
     * render a 'preview no longer available' message. */
    expect(getPreview("nonexistent-id")).toBeUndefined();
  });

  it("each storePreview call returns a unique ID", () => {
    /** Different storage calls must yield different IDs even with
     * identical content — otherwise two admins previewing the same
     * template would collide. */
    const id1 = storePreview("same content");
    const id2 = storePreview("same content");
    expect(id1).not.toBe(id2);
  });

  it("preview is automatically deleted after TTL (10 minutes)", () => {
    /** Pin the 10-minute TTL — short enough to prevent unbounded
     * memory growth, long enough to outlast typical edit-preview
     * cycles. */
    const id = storePreview("<p>Body</p>");
    expect(getPreview(id)).toBe("<p>Body</p>");

    // Fast-forward just under TTL — should still be there.
    jest.advanceTimersByTime(10 * 60 * 1000 - 1);
    expect(getPreview(id)).toBe("<p>Body</p>");

    // Cross the TTL boundary.
    jest.advanceTimersByTime(2);
    expect(getPreview(id)).toBeUndefined();
  });

  it("store survives module re-import (pinned to globalThis)", () => {
    /** SECURITY-ADJACENT: the globalThis pinning is the load-bearing
     * detail that makes POST + GET in different Next.js bundles see
     * the same Map. If a future refactor uses a plain module-level
     * Map, this test catches the regression — re-requiring the
     * module must keep the same store reference.
     *
     * We probe this by storing, deleting Node's require cache,
     * re-importing, and reading. */
    const id = storePreview("<p>Persistent body</p>");

    // Simulate bundle reload by clearing the module's require cache.
    jest.resetModules();
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const reloaded = require("../email-preview-store") as typeof import("../email-preview-store");

    expect(reloaded.getPreview(id)).toBe("<p>Persistent body</p>");
  });
});
