name: vscode-tunnel

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: scholarship

    steps:
      - name: Start tunnel
        run: |
          ./vscode tunnel \
            --accept-server-license-terms \
            --name my-work-server
